# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-13 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('subtitle', models.CharField(max_length=256, verbose_name='Subtitle')),
                ('image', models.CharField(max_length=256, verbose_name='Image')),
                ('price', models.FloatField(verbose_name='Price')),
                ('hitcount', models.IntegerField(verbose_name='HitCount')),
            ],
        ),
    ]
